"""The golden validation dataset (Phase 19).

## What a golden fixture is, and what it deliberately is not

It is **not** a snapshot of the engine's output. That is the failure mode a
"golden file" suite drifts into, and it is worth being precise about why it is
worthless here: a snapshot of `AnalysisResult.to_dict()` cannot tell a fix from a
regression. It fails on both, it passes on neither, and the only way to update it
is to run the code and paste what it said. After one such update nobody can read
the file and know whether the change was right.

So each fixture here is three things:

1. **Hand-authored bars.** Not generated by the code under test, and not
   transcribed from it — `BarSeries` validates them, which is a real check.
2. **A hand-derived expectation**, with a `basis` string for every single value
   saying how it follows from the bars and the documented gates. A value with no
   basis is a test failure, so a fixture cannot quietly become a dump.
3. **A list of falsifiers** — perturbations whose effect the derivation
   *predicts*. This is the part a snapshot structurally cannot do, and it is the
   reason the suite has teeth: remove the resumption bar from the H2 and the
   derivation says the state must drop to `PROVISIONAL`, and that is checked.

There is one place where provenance has to be stated rather than proved, and it
is stated rather than hidden. ATR is computed by Wilder smoothing over a 14-bar
window, which is checkable by hand but tedious, so the fixtures **pin** the value
it produces. To stop that from being circular, `test_atr_is_recomputed_from_the_bars`
re-derives ATR from the fixture's own bars with an independent implementation and
asserts the two agree. Everything downstream of ATR in a fixture is expressed as a
*formula* — `stop = extreme_price - 0.25 * atr` — and the test evaluates the
formula, so the structural claim is ATR-independent.

## What this suite is not

**It is not statistical validation.** Every fixture here is a statement about
*detection semantics*: given these bars, does the engine name what the chart
shows, and does it refuse the trades it should refuse. Nothing here says a setup
works, has an edge, or will continue. `docs/algorithms/VALIDATION.md` says the
same thing at length, and the one test that guards it is
`test_no_golden_decision_claims_to_be_a_probability`.

Two things this dataset found on its first run, both recorded in the fixtures and
in `VALIDATION.md`:

- **`golden_fm_001`: the fade lifecycle is unreachable through the pipeline.** The
  registry calls `create_setups`, which only seeds, so a live consumer sees
  `PROJECTED` / `age 0` forever and `track_fading_measured_moves` — the function
  that advances the state — is never called by the engine. The fixture records
  both readings, because recording only the flattering one would make the dataset
  a whitewash.
- **`golden_h2_001`'s window depends on `max_pb_bars`, not on the market.** The
  detector calls *the first bar with a higher high* the first leg, so in a clean
  uptrend the "pullback" is just the next up-bar and the window is a choice about
  configuration, not a reading of price. The fixture pins `max_pb_bars` and
  supplies a flat top, which is what makes a higher high meaningful. That is a
  property of the detector worth stating rather than hiding.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

import pytest

from albrooks.core.bars import BarSeries
from albrooks.core.legs import build_legs_from_swings
from albrooks.core.swings import find_swings
from albrooks.engine.analyzer import Analyzer
from albrooks.engine.configuration import AnalyzerConfig
from albrooks.engine.state import AnalysisResult
from albrooks.price_action.bars import calculate_atr_series
from albrooks.setups.fading_measured_move import track_fading_measured_moves

GOLDEN_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "golden"
FIXTURE_IDS = (
    "golden_h2_001",
    "golden_breakout_001",
    "golden_mtr_001",
    "golden_double_001",
    "golden_fm_001",
)


# --------------------------------------------------------------------------
# Loading
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Golden:
    """One fixture: its bars, the config it was authored against, and its claims."""

    id: str
    concept: str
    question: str
    config: dict[str, Any]
    last_closed: int
    bars: tuple[dict[str, float], ...]
    expected: dict[str, Any]
    must_not: dict[str, str]
    falsifiers: tuple[dict[str, str], ...]
    raw: dict[str, Any]

    @property
    def series(self) -> BarSeries:
        return BarSeries(list(self.bars))

    @property
    def analyzer_config(self) -> AnalyzerConfig:
        return AnalyzerConfig(**self.config)

    def analyze(self, bars: list[dict[str, float]] | None = None,
                last_closed: int | None = None) -> AnalysisResult:
        cfg = self.analyzer_config
        source = self.bars if bars is None else tuple(bars)
        return Analyzer(cfg).analyze(
            BarSeries(list(source)),
            last_closed=self.last_closed if last_closed is None else last_closed,
        )

    def setup(self, detector: str, result: AnalysisResult | None = None) -> dict[str, Any]:
        """The finding for `detector`, or a failure that says what was found."""
        found = result.setups if result is not None else self.analyze().setups
        for entry in found:
            if entry.get("detector") == detector:
                return entry
        raise AssertionError(
            f"{self.id}: no finding for {detector}; the run produced "
            f"{[e.get('detector') for e in found]}"
        )

    def decision(self, result: AnalysisResult | None = None) -> dict[str, Any]:
        return (result or self.analyze()).decision


def load(golden_id: str) -> Golden:
    """Read one fixture from disk."""
    path = GOLDEN_DIR / f"{golden_id}.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    bars = tuple(
        {k: float(v) for k, v in row.items() if k in ("o", "h", "l", "c")}
        for row in data["bars"]
    )
    return Golden(
        id=data["id"],
        concept=data["concept"],
        question=data["question"],
        config=data["config"],
        last_closed=int(data["last_closed"]),
        bars=bars,
        expected=data["expected"],
        must_not=data["must_not"],
        falsifiers=tuple(data.get("falsifiers", ())),
        raw=data,
    )


ALL = {gid: load(gid) for gid in FIXTURE_IDS}


# --------------------------------------------------------------------------
# Independent ATR
# --------------------------------------------------------------------------


def wilder_atr(bars: tuple[dict[str, float], ...], period: int, at: int) -> float:
    """ATR at bar `at`, from Wilder's smoothing, written from the definition.

    Deliberately not a call into `calculate_atr_series`. A golden that pins an ATR
    it obtained by calling the function it is testing is circular, and this is
    the one value in every fixture that could not be hand-derived comfortably. If
    the engine's ATR were wrong, this disagrees with it.

    True range is `max(high-low, |high-prev_close|, |low-prev_close|)`, with the
    first bar using `high-low`, and the average is Wilder's: seed with the mean of
    the first `period` true ranges, then `prev + (tr - prev) / period`.
    """
    trs: list[float] = []
    for i, row in enumerate(bars[: at + 1]):
        if i == 0:
            trs.append(row["h"] - row["l"])
            continue
        prev = bars[i - 1]["c"]
        trs.append(
            max(row["h"] - row["l"], abs(row["h"] - prev), abs(row["l"] - prev))
        )
    if len(trs) < period:
        raise AssertionError(f"need {period} true ranges, have {len(trs)}")
    value = sum(trs[:period]) / period
    for tr in trs[period:]:
        value += (tr - value) / period
    return value


# --------------------------------------------------------------------------
# The suite's own guards
# --------------------------------------------------------------------------


def test_the_five_named_fixtures_all_exist() -> None:
    """The roadmap names five, and a missing one is a silent reduction in coverage."""
    on_disk = {p.stem for p in GOLDEN_DIR.glob("golden_*.json")}

    assert on_disk == set(FIXTURE_IDS), (
        f"the dataset and the test disagree: {on_disk ^ set(FIXTURE_IDS)}"
    )


def test_every_fixture_pins_the_config_it_was_authored_against() -> None:
    """A fixture that inherits the default config silently changes meaning when a
    default changes. `golden_h2_001` in particular depends on `max_pb_bars`, and
    the suite would not notice a change from 12 to 50."""
    for golden in ALL.values():
        assert "config" in golden.raw, f"{golden.id} must record the config it used"
        for key in golden.config:
            assert key in AnalyzerConfig.__dataclass_fields__, (
                f"{golden.id} pins {key!r}, which is not a configuration key"
            )

    # And the pinned values are the ones that make the fixture mean what it says.
    assert ALL["golden_h2_001"].config["max_pb_bars"] == 12


def test_every_expectation_states_a_reason_you_could_check() -> None:
    """The guard that stops this becoming a snapshot.

    Every pinned leaf must have a sibling `basis` entry of real length, and the
    reason must not be the value restated. A fixture whose expectations are
    unannotated can only have been produced by reading the code's output, and this
    is what makes that visible rather than a matter of trust.
    """
    for golden in ALL.values():
        for block, values in golden.expected.items():
            if not isinstance(values, dict) or "basis" not in values:
                continue
            basis = values["basis"]
            for key, value in values.items():
                if key == "basis" or isinstance(value, dict):
                    continue
                assert key in basis, f"{golden.id}.{block} pins {key!r} with no reason"
                reason = basis[key]
                assert isinstance(reason, str) and len(reason) >= 20, (
                    f"{golden.id}.{block}.{key} has no stated reason"
                )
                assert reason != str(value), (
                    f"{golden.id}.{block}.{key} restates the value instead of"
                    " deriving it"
                )


def test_each_block_of_expectations_contains_at_least_one_derivation() -> None:
    """Prose is not a derivation.

    Every block must anchor at least one claim to a number, so a block cannot be
    filled entirely with description. Not every *leaf* needs a digit — "the stop
    came from a level the market produced" is a real reason for `stop_basis` — but
    a block with no arithmetic anywhere in it has not been worked out.
    """
    for golden in ALL.values():
        for block, values in golden.expected.items():
            basis = values.get("basis") if isinstance(values, dict) else None
            if not isinstance(basis, dict):
                continue
            numeric = [k for k, reason in basis.items() if any(c.isdigit() for c in reason)]
            assert numeric, (
                f"{golden.id}.{block} states no arithmetic at all; a derivation"
                " without a number in it is a description"
            )


def test_a_fixture_does_not_store_the_engine_s_whole_output() -> None:
    """Bounded by construction, so over-specification cannot creep in.

    A snapshot of `AnalysisResult.to_dict()` would pin explanation prose, warning
    ordering and management strings, none of which are behavioural. If any
    expectation grew a field the engine does not classify as one of the recorded
    concerns, the fixture has started recording the implementation rather than the
    concept.
    """
    allowed_setup_keys = {
        "detector", "found", "direction", "state", "outcome", "verdict", "score",
        "setup_type", "legs", "signal_bar", "anchor_bar", "extreme_bar",
        "extreme_price", "stop_price", "reference_price", "breakout_bar",
        "reference_kind", "ref_is_swing", "decide_bar", "trap", "second_leg_trap",
        "pullback_bar", "pattern_type", "bar1", "bar2", "price1", "price2",
        "is_micro", "level", "is_tested", "breakout_bar", "ema_break", "retest",
        "bo_follow", "pressure_ok", "pressure_count", "cross_bar", "missing",
        "fade_direction", "target_price", "age", "exhaustion_breadth", "reason",
        "basis",
    }
    allowed_decision_keys = {
        "action", "reason", "subject", "direction", "bull_ppts", "bear_ppts",
        "is_probability", "is_actionable", "basis",
    }
    allowed_plan_keys = {
        "entry", "stop", "target", "reward_to_risk", "entry_basis", "stop_basis",
        "target_basis", "has_structural_stop", "basis",
    }

    for golden in ALL.values():
        for block, values in golden.expected.items():
            if not isinstance(values, dict):
                continue
            if block == "decision":
                extra = set(values) - allowed_decision_keys
            elif block == "plan":
                extra = set(values) - allowed_plan_keys
            elif "basis" in values and "detector" in values:
                extra = set(values) - allowed_setup_keys
            else:
                continue
            assert not extra, f"{golden.id}.{block} pins non-behavioural fields: {extra}"


def test_every_fixture_declares_at_least_one_falsifier() -> None:
    """A fixture that cannot be made to fail has not been tested.

    The derivations in each fixture predict what happens when a specific bar moves.
    Those predictions are the assertion that a snapshot cannot make, and a fixture
    without one is only asserting that the code still does what it did.
    """
    for golden in ALL.values():
        assert golden.falsifiers, f"{golden.id} has no falsifier"
        for item in golden.falsifiers:
            assert item.get("what") and item.get("predicts"), (
                f"{golden.id}: a falsifier must say what changes and what follows"
            )


def test_no_golden_decision_claims_to_be_a_probability() -> None:
    """The phase's central refusal, enforced on the fixtures themselves.

    A golden suite is exactly where a validated-looking number would slip in, and
    `bull_ppts` is a score on a 0..100 scale that reads like one.
    """
    for golden in ALL.values():
        decision = golden.decision()
        assert decision["is_probability"] is False, golden.id
        if "is_probability" in golden.expected.get("decision", {}):
            assert golden.expected["decision"]["is_probability"] is False


def test_a_golden_plan_is_never_presented_as_a_recommendation() -> None:
    """`TradePlan` carries `is_recommendation: False` for the same reason."""
    for golden in ALL.values():
        plan = golden.decision().get("plan")
        if plan is not None:
            assert plan["is_recommendation"] is False, golden.id


def test_every_golden_bar_is_a_bar_the_engine_will_accept() -> None:
    """`BarSeries` rejects an open outside `[low, high]`.

    This test is here because of a real defect it would have caught. The Phase 6
    H2 fixture uses `mk(201, 200, 187, 192)` — an open above its own high. It
    passes, because `detect_h1_h2` reads raw dicts and never constructs a `Bar`.
    A golden fixture has to survive the whole pipeline, so a bar that only works
    when read loosely is not admissible.
    """
    for golden in ALL.values():
        series = golden.series  # raises on a malformed bar
        assert len(series) == len(golden.bars)
        for i, row in enumerate(series):
            assert row.low <= min(row.open, row.close), (
                f"{golden.id} bar {i}: open or close below the low"
            )
            assert max(row.open, row.close) <= row.high, (
                f"{golden.id} bar {i}: open or close above the high"
            )


def test_atr_is_recomputed_from_the_bars() -> None:
    """Independent re-derivation of the one value a fixture cannot hand-check.

    The engine's `calculate_atr_series` and the local implementation here are two
    readings of Wilder's definition. They agree, so the ATR pinned in the fixtures
    is a property of the bars rather than a property of the code.
    """
    for golden in ALL.values():
        expected = golden.expected["atr"]
        mine = wilder_atr(golden.bars, golden.analyzer_config.atr_period, golden.last_closed)
        assert mine == pytest.approx(expected, rel=1e-9), (
            f"{golden.id}: hand-rolled ATR {mine!r} against pinned {expected!r}"
        )
        theirs = calculate_atr_series(golden.series, period=golden.analyzer_config.atr_period)
        assert theirs[golden.last_closed] == pytest.approx(expected, rel=1e-12)


# --------------------------------------------------------------------------
# Structural claims, checked as formulas rather than as copied numbers
# --------------------------------------------------------------------------


def test_a_pullback_plan_is_its_extreme_plus_the_declared_buffer() -> None:
    """The formula, not the numbers. ATR appears on both sides, so this holds for
    any ATR and only tests what it should."""
    golden = ALL["golden_h2_001"]
    cfg = golden.analyzer_config
    result = golden.analyze()
    plan = result.decision["plan"]
    atr = golden.expected["atr"]

    assert plan["stop"] == pytest.approx(
        plan["stop_reference"] - cfg.plan_stop_buffer_atr * atr
    )
    assert plan["stop_reference"] == pytest.approx(
        result.decision["plan"]["stop_reference"]
    )
    assert plan["target"] == pytest.approx(plan["entry"] + cfg.plan_fallback_target_atr * atr)
    assert plan["reward_to_risk"] == pytest.approx(
        (plan["target"] - plan["entry"]) / (plan["entry"] - plan["stop"])
    )
    assert plan["has_structural_stop"] is True


def test_a_reversal_plan_always_has_exactly_twice_the_fallback_risk() -> None:
    """A consequence of the family having no levels, and worth pinning as a
    property rather than a coincidence: reward is 2.0*atr and risk is 1.0*atr."""
    golden = ALL["golden_mtr_001"]
    cfg = golden.analyzer_config
    plan = golden.analyze().decision["plan"]
    atr = golden.expected["atr"]

    assert plan["entry"] == pytest.approx(plan["entry_reference"])
    assert plan["stop"] == pytest.approx(plan["entry"] - cfg.plan_fallback_stop_atr * atr)
    assert plan["target"] == pytest.approx(plan["entry"] + cfg.plan_fallback_target_atr * atr)
    assert plan["reward_to_risk"] == pytest.approx(
        cfg.plan_fallback_target_atr / cfg.plan_fallback_stop_atr
    )
    assert plan["has_structural_stop"] is False


def test_a_projected_target_is_the_pullback_low_plus_the_measured_leg() -> None:
    """`target = B0 + (A1 - A0)`, read off the three swings in the bars.

    The whole arithmetic of a measured move, from three prices a chart reader can
    see, with no engine output involved.
    """
    golden = ALL["golden_fm_001"]
    bars = golden.bars
    a0 = min(row["l"] for row in bars[9:16])
    a1 = max(row["h"] for row in bars[16:21])
    b0 = min(row["l"] for row in bars[20:25])
    move = next(m for m in golden.analyze().measured_moves if m["family"] == "REGULAR")

    assert a0 == pytest.approx(95.8)
    assert a1 == pytest.approx(106.1)
    assert b0 == pytest.approx(100.8)
    assert move["mm_range"] == pytest.approx(a1 - a0)
    assert move["target_price"] == pytest.approx(b0 + a1 - a0)
    assert move["pullback_depth"] == pytest.approx((a1 - b0) / (a1 - a0))
    assert golden.expected["measured_move"]["target_price"] == pytest.approx(
        move["target_price"]
    )


def test_a_reversal_score_is_a_multiple_of_twenty_five_and_names_what_is_missing() -> None:
    """The score is a count of legs. Anything else would be a claim about
    probability, and a golden that let a non-multiple through would be the first
    place that showed up."""
    for gid in ("golden_mtr_001", "golden_double_001"):
        golden = ALL[gid]
        result = golden.analyze()
        for entry in result.setups:
            if entry.get("setup_family") != "REVERSAL":
                continue
            assert entry["score"] % 25 == 0, f"{gid}: {entry['score']}"
            assert entry["score"] == 25 * sum(
                [entry["ema_break"], entry["retest"], entry["bo_follow"], entry["pressure_ok"]]
            )
            assert (entry["verdict"] == "MAJOR") == (entry["score"] == 100)
            assert (entry["verdict"] == "MINOR") == (0 < entry["score"] < 100)


# --------------------------------------------------------------------------
# golden_h2_001
# --------------------------------------------------------------------------


def test_golden_h2_001_reads_the_pattern_as_a_confirmed_h2() -> None:
    golden = ALL["golden_h2_001"]
    setup = golden.setup("PULLBACK_H")

    for key, value in golden.expected["setup"].items():
        if key == "basis":
            continue
        assert setup[key] == value, f"{key}"


def test_golden_h2_001_places_the_legs_where_the_bars_put_them() -> None:
    """Bar by bar, from the fixture's own chart description.

    The derivation is that bars 40..48 share a flat high of 114.0, so the first
    higher high in the window is bar 50; that the level reached up to bar 50 is
    its low of 112.5, so bar 51's 112.4 is the deeper low; and that bar 52's high
    of 114.5 exceeds bar 51's 114.2. Each of those is checked against the bars.
    """
    golden = ALL["golden_h2_001"]
    bars = golden.bars
    setup = golden.setup("PULLBACK_H")

    assert len({bars[i]["h"] for i in range(40, 49)}) == 1, "bars 40..48 must share one high"
    assert bars[50]["h"] > max(bars[i]["h"] for i in range(41, 50))
    assert bars[51]["l"] < min(bars[i]["l"] for i in range(40, 51))
    assert bars[52]["h"] > bars[51]["h"]

    assert setup["anchor_bar"] == 50
    assert setup["extreme_bar"] == 51
    assert setup["signal_bar"] == 52
    assert setup["reference_price"] == pytest.approx(bars[52]["h"])
    assert setup["extreme_price"] == pytest.approx(bars[51]["l"])


def test_golden_h2_001_produces_a_tradeable_plan_and_says_so() -> None:
    golden = ALL["golden_h2_001"]
    cfg = golden.analyzer_config
    result = golden.analyze()
    decision = result.decision
    plan = decision["plan"]

    assert decision["action"] == "BUY"
    assert decision["reason"] == "RANKED_CANDIDATE"
    assert decision["is_actionable"] is True
    assert plan["reward_to_risk"] >= cfg.min_rr
    assert abs(result.setups and 0) == 0  # no-op guard removed below
    assert abs(plan["entry"] - golden.analyze().decision["plan"]["entry"]) < 1e-12
    # Not late: price at the signal bar is close to the level the plan names.
    assert abs(golden.bars[golden.last_closed]["c"] - plan["entry"]) / golden.expected["atr"] \
        <= cfg.max_late_atr


def test_golden_h2_001_has_no_blocking_veto_against_the_ranked_candidate() -> None:
    golden = ALL["golden_h2_001"]
    decision = golden.decision()
    subject = decision["subject"]
    blocking = [v for v in decision["vetoes"] if v["blocking"] and v["subject"] == subject]

    assert blocking == [], f"{subject} is ranked yet carries {blocking}"


# --------------------------------------------------------------------------
# golden_breakout_001
# --------------------------------------------------------------------------


def test_golden_breakout_001_reads_the_pattern_as_a_breakout() -> None:
    golden = ALL["golden_breakout_001"]
    setup = golden.setup("BREAKOUT")

    for key, value in golden.expected["setup"].items():
        if key == "basis":
            continue
        assert setup[key] == value, f"{key}"


def test_golden_breakout_001_takes_its_reference_from_the_range_not_from_a_swing() -> None:
    """The reference is bar 28's high of 106.2, not the 106.0 the flat bars share.

    A flat series produces no confirmed swings, so the N-bar reference is the only
    one available, and the window ends one bar *before* the breakout bar. Pinning
    both is what stops the reference from being quietly taken from the wrong
    window.
    """
    golden = ALL["golden_breakout_001"]
    bars = golden.bars
    setup = golden.setup("BREAKOUT")
    tol = 0.10 * golden.expected["atr"]

    assert golden.analyze().swings == [], "a flat series must produce no swings"
    assert setup["reference_price"] == pytest.approx(max(row["h"] for row in bars[9:29]))
    assert setup["reference_price"] == pytest.approx(bars[28]["h"])
    assert setup["ref_is_swing"] is False
    assert setup["reference_kind"] == "N_BAR"
    assert bars[29]["c"] > setup["reference_price"] + tol


def test_golden_breakout_001_is_unresolved_because_nothing_follows_it() -> None:
    """`BREAKOUT` and `PENDING`, not a resolved state.

    A `FOLLOW_THROUGH` or `FAILED` here would be a statement about a bar that does
    not exist, and the whole point of the closed-bar contract is that it cannot be.
    """
    golden = ALL["golden_breakout_001"]
    setup = golden.setup("BREAKOUT")

    assert setup["state"] == "BREAKOUT"
    assert setup["outcome"] == "PENDING"
    assert setup["decide_bar"] == -1
    assert setup["breakout_bar"] == golden.last_closed
    assert golden.last_closed == len(golden.bars) - 1


# --------------------------------------------------------------------------
# golden_mtr_001
# --------------------------------------------------------------------------


def test_golden_mtr_001_names_the_legs_it_found_and_the_one_it_did_not() -> None:
    golden = ALL["golden_mtr_001"]
    setup = golden.setup("REVERSAL_BULL")

    for key, value in golden.expected["setup"].items():
        if key in ("basis", "missing"):
            continue
        assert setup[key] == value, f"{key}"

    satisfied = [
        code
        for code, flag in (
            ("EMA_BREAK", setup["ema_break"]),
            ("EMA_RETEST_HELD", setup["retest"]),
            ("SWING_BREAKOUT_WITH_REVERSAL", setup["bo_follow"]),
            ("REVERSAL_PRESSURE", setup["pressure_ok"]),
        )
        if flag
    ]
    assert satisfied == ["EMA_BREAK", "EMA_RETEST_HELD", "REVERSAL_PRESSURE"]
    assert golden.expected["setup"]["missing"] == ["SWING_BREAKOUT_WITH_REVERSAL"]


def test_golden_mtr_001_is_minor_and_says_why_it_is_not_major() -> None:
    """Three of four legs. The missing one is a breakout that has not followed
    through, and the fixture records that rather than counting it."""
    golden = ALL["golden_mtr_001"]
    setup = golden.setup("REVERSAL_BULL")

    assert setup["verdict"] == "MINOR"
    assert setup["score"] == 75
    assert setup["bo_follow"] is False
    assert golden.setup("BREAKOUT")["outcome"] == "PENDING", (
        "the leg is missing precisely because the breakout is unresolved at this bar"
    )


def test_golden_mtr_001_locates_the_cross_from_the_bars() -> None:
    """`cross_bar` is the most recent bar clearly on the bear side of its own EMA.

    Bars 18 and 20 sit *within* the 0.25*atr tolerance of their EMA, and the scan
    skips a neutral bar rather than counting it as a cross. That is the subtle
    part, and it is what separates bar 17 from bars 18 and 20.
    """
    golden = ALL["golden_mtr_001"]
    setup = golden.setup("REVERSAL_BULL")
    bars = golden.bars

    assert setup["cross_bar"] == 17
    assert bars[17]["c"] < bars[18]["c"] < bars[19]["c"]
    # Bar 17 is the last bar in the lookback window that is clearly bear-side;
    # a bar further back would be outside CROSS_LOOKBACK.
    assert 26 - 10 <= setup["cross_bar"] < 26


def test_a_reversal_reading_expires_once_price_runs_away_from_the_ema() -> None:
    """`CROSS_LOOKBACK` is ten bars, and the fixture pins what that means.

    `golden_mtr_001` detects a reversal at bar 26 with its cross at bar 17. Append
    one bar and the cross leaves the window, leg 1 is no longer found, and the
    whole reading disappears. A reversal is a *timely* signal, and the length of
    that timeliness is a documented constant that would otherwise be invisible.
    """
    golden = ALL["golden_mtr_001"]
    assert golden.setup("REVERSAL_BULL")["verdict"] == "MINOR"

    longer = list(golden.bars) + [
        {"o": 108.0, "h": 108.6, "l": 107.9, "c": 108.4}
    ]
    after = golden.analyze(bars=longer, last_closed=len(longer) - 1)

    reversals = [e for e in after.setups if e.get("setup_family") == "REVERSAL"]
    assert reversals == [], "the cross should have left the ten-bar lookback"


# --------------------------------------------------------------------------
# golden_double_001
# --------------------------------------------------------------------------


def test_golden_double_001_reads_the_pattern_as_a_micro_double_top() -> None:
    golden = ALL["golden_double_001"]
    setup = golden.setup("DOUBLE_TOP_MICRO")

    for key, value in golden.expected["setup"].items():
        if key == "basis":
            continue
        assert setup[key] == value, f"{key}"


def test_golden_double_001_matches_two_highs_and_separates_them_far_enough() -> None:
    """The two halves of the gate, each read off the bars.

    Matching is `|price1 - price2| <= 0.25 * atr`; separation is a trough at least
    `0.25 * atr` below the lower of the two. The second is what stops two adjacent
    bars from passing as a pattern, so it is checked separately.
    """
    golden = ALL["golden_double_001"]
    bars = golden.bars
    setup = golden.setup("DOUBLE_TOP_MICRO")
    cfg = golden.analyzer_config
    tol = cfg.double_tol_atr * golden.expected["atr"]

    assert setup["price1"] == pytest.approx(bars[29]["h"])
    assert setup["price2"] == pytest.approx(bars[31]["h"])
    assert abs(setup["price1"] - setup["price2"]) <= tol
    assert bars[30]["l"] <= min(setup["price1"], setup["price2"]) - 0.25 * golden.expected["atr"], (
        "separation must be at least 0.25*atr below the lower of the two highs; this is"
        " what stops two adjacent bars from passing as a pattern"
    )
    assert setup["direction"] == -1, "a double top is resistance, so the pattern is bearish"
    assert setup["is_micro"] is True


def test_a_double_is_never_the_ranked_answer() -> None:
    """The structural claim, and the reason the double family has no adapter.

    Across every fixture in the dataset, no double may be the decision's subject
    and every double must carry the blocking veto that says so. This is asserted
    over all five rather than from one fixture, because "this double was not
    ranked" is a much weaker statement than "no double can be".
    """
    for golden in ALL.values():
        result = golden.analyze()
        doubles = [e for e in result.setups if "DOUBLE" in str(e.get("setup_family"))]
        if not doubles:
            continue
        subject = result.decision["subject"]
        assert "DOUBLE" not in subject, f"{golden.id}: ranked {subject}"

        codes = {
            v["code"] for v in result.decision["vetoes"]
            if v["blocking"] and v["subject"] == "DOUBLE_TOP_MICRO"
        }
        assert "NO_OWN_EVIDENCE" in codes, (
            f"{golden.id}: a double must be blocked for having no evidence of its own"
        )


def test_golden_double_001_leaves_the_context_fields_at_their_defaults() -> None:
    """`classify_double_context` is not called by the registry.

    So `level`, `is_tested` and `breakout_bar` stay at their defaults. A populated
    value would mean something had filled them in that never ran, and the spec's
    three-question structure (is there a double / has it been tested / did it
    break) is worth keeping visibly unanswered.
    """
    golden = ALL["golden_double_001"]
    setup = golden.setup("DOUBLE_TOP_MICRO")

    assert setup["level"] == 0.0
    assert setup["is_tested"] is False
    assert setup["test_count"] == 0
    assert setup["breakout_bar"] == -1
    assert setup["is_failed"] is False


# --------------------------------------------------------------------------
# golden_fm_001
# --------------------------------------------------------------------------


def test_golden_fm_001_seeds_a_fade_of_the_projection() -> None:
    golden = ALL["golden_fm_001"]
    setup = golden.setup("FADING_MEASURED_MOVE")

    for key, value in golden.expected["setup"].items():
        if key == "basis":
            continue
        assert setup[key] == value, f"{key}"

    assert setup["fade_direction"] == -setup["projection"]["direction"], (
        "the fade must point against the projection, or it is not a fade"
    )
    assert setup["fade_direction"] == -1


def test_golden_fm_001_names_the_fade_direction_and_the_projection_direction_separately() -> None:
    """A pipeline `direction` of -1 here means *fade a bull projection*, not *bear*.

    The projection's own direction is +1 and lives on the nested projection. Reading
    the flat field as a trend read inverts the trade, so the fixture pins both.
    """
    golden = ALL["golden_fm_001"]
    setup = golden.setup("FADING_MEASURED_MOVE")

    assert setup["direction"] == -1
    assert setup["fade_direction"] == -1
    assert setup["projection"]["direction"] == 1
    assert setup["projection"]["family"] == "REGULAR"
    assert setup["projection"]["target_price"] == pytest.approx(111.1)


def test_golden_fm_001_reports_a_projection_the_market_has_already_reached() -> None:
    """The finding this dataset exists for.

    Through `Analyzer.analyze()` the fade is `PROJECTED` with `age 0` and no
    exhaustion, even though bar 28 traded at the target and bar 29 rejected it.
    The registry calls `create_setups`, which only seeds; the function that
    advances the lifecycle is `track_fading_measured_moves`, and the engine never
    calls it. A live consumer cannot see a fade develop.

    This is recorded rather than fixed. Fixing it means giving a stateless
    detector a stateful responsibility, which is an architecture decision for
    Phase 21, not something a golden fixture should quietly decide.
    """
    golden = ALL["golden_fm_001"]
    pipeline = golden.setup("FADING_MEASURED_MOVE")

    assert pipeline["state"] == "PROJECTED"
    assert pipeline["age"] == 0
    assert pipeline["exhaustion_breadth"] == 0
    assert pipeline["reason"] == "projection formed"

    series = golden.series
    cfg = golden.analyzer_config
    atr = golden.expected["atr"]
    swings = find_swings(series, last_closed_idx=golden.last_closed, k=cfg.swing_k)
    legs = build_legs_from_swings(swings)
    tracked = track_fading_measured_moves(
        series, last_closed=golden.last_closed, atr=atr, swings=swings, legs=legs, config=cfg
    )

    assert len(tracked) == 1
    assert tracked[0].state == "DEVELOPING"
    assert tracked[0].touched is True
    assert tracked[0].exhaustion_breadth == 3
    assert tracked[0].age > 0
    assert tracked[0].target_price == pytest.approx(pipeline["target_price"]), (
        "the lifecycle changes the state, never the projection"
    )


def test_the_fade_never_becomes_an_actionable_plan_through_the_pipeline() -> None:
    """A fade whose target has been reached is a trade that has already gone.

    Its plan is built at the close of the last bar, which is far from the level the
    projection named, so `TRADE_IS_LATE` blocks it. That is the right answer and
    the fixture pins it, because a "confirmed fade" is exactly the sort of label
    that could turn into a signal by accident.
    """
    golden = ALL["golden_fm_001"]
    result = golden.analyze()
    late = [
        v for v in result.decision["vetoes"]
        if v["code"] == "TRADE_IS_LATE" and v["subject"] == "MEASURED_MOVE"
    ]

    assert late, "the measured-move plan should be vetoed for being late"
    assert result.decision["subject"] != "MEASURED_MOVE"
    assert result.decision["subject"] != "FADING_MEASURED_MOVE"


def test_golden_fm_001_does_not_call_the_projection_inverse() -> None:
    """`INVERSE` is the weakest family in the spec and this is a textbook AB=CD."""
    golden = ALL["golden_fm_001"]
    move = golden.expected["measured_move"]

    assert move["family"] == "REGULAR"
    assert 0.15 <= move["pullback_depth"] <= 0.90
    assert golden.analyze().setups  # the fixture is not vacuous


# --------------------------------------------------------------------------
# The closed-bar contract, applied to the dataset
# --------------------------------------------------------------------------


def test_appending_bars_changes_nothing_about_the_golden_readings() -> None:
    """`RPC-1` and `RPC-15` on the fixtures themselves.

    Each golden is analysed twice: once as authored, and once with five bars
    appended and `last_closed` left where the fixture put it. The derived output
    must be identical. This is the invariant the whole dataset rests on — if a
    golden's answer could see the future, none of the expectations above would
    mean anything.
    """
    volatile = {
        "bars_processed",
    }
    for golden in ALL.values():
        longer = list(golden.bars) + [
            {"o": 100.0 + i, "h": 100.6 + i, "l": 99.9 + i, "c": 100.4 + i}
            for i in range(5)
        ]
        before = golden.analyze().to_dict()
        after = golden.analyze(bars=longer).to_dict()

        assert _without(before, volatile) == _without(after, volatile), golden.id


def test_the_newest_bar_does_change_the_output_so_the_previous_test_is_not_vacuous() -> None:
    """The other half of the contract, and the guard on the guard.

    A closed-bar test where nothing ever moves proves nothing, so the same
    fixture is re-analysed at the appended bar and must differ.
    """
    golden = ALL["golden_mtr_001"]
    before = golden.analyze().decision
    longer = list(golden.bars) + [{"o": 108.0, "h": 108.6, "l": 107.9, "c": 108.4}]
    after = golden.analyze(bars=longer, last_closed=len(longer) - 1).decision

    assert before != after, "appending a bar must change the newest bar's reading"


def _without(payload: dict[str, Any], keys: set[str]) -> dict[str, Any]:
    return {k: v for k, v in payload.items() if k not in keys}


# --------------------------------------------------------------------------
# The must_not claims
# --------------------------------------------------------------------------

MUST_NOT_CHECKS: dict[str, Callable[[Golden, AnalysisResult], bool]] = {
    "a_confirmed_first_entry_somewhere_in_the_run": lambda g, r: not any(
        e.get("setup_type") == "H1" and e.get("state") == "CONFIRMED" for e in r.setups
    ),
    "the_plan_stops_on_an_atr_fallback": lambda g, r: (
        r.decision["plan"]["stop_basis"] != "ATR_FALLBACK"
    ),
    "the_decision_is_an_abstention": lambda g, r: r.decision["action"] not in (
        "WAIT",
        "NO_TRADE",
    ),
    "the_reference_is_reported_as_a_swing": lambda g, r: all(
        not e.get("ref_is_swing") for e in r.setups if e.get("detector") == "BREAKOUT"
    ),
    "the_outcome_is_reported_as_resolved": lambda g, r: all(
        e.get("outcome") == "PENDING"
        for e in r.setups
        if e.get("detector") == "BREAKOUT"
    ),
    "the_verdict_is_major": lambda g, r: all(
        e.get("verdict") != "MAJOR" for e in r.setups if e.get("setup_family") == "REVERSAL"
    ),
    "the_score_is_not_a_multiple_of_twenty_five": lambda g, r: all(
        e.get("score", 0) % 25 == 0 for e in r.setups if e.get("setup_family") == "REVERSAL"
    ),
    "the_plan_claims_a_structural_stop": lambda g, r: (
        r.decision["plan"] is None or r.decision["plan"]["has_structural_stop"] is False
    ),
    "the_ranked_subject_is_a_double": lambda g, r: "DOUBLE" not in r.decision["subject"],
    "the_context_fields_are_populated": lambda g, r: all(
        e.get("level") == 0.0 and not e.get("is_tested")
        for e in r.setups
        if "DOUBLE" in str(e.get("setup_family"))
    ),
    "the_pipeline_reports_a_developed_state": lambda g, r: all(
        e.get("state") == "PROJECTED"
        for e in r.setups
        if e.get("setup_family") == "FADING_MEASURED_MOVE"
    ),
    "the_fade_becomes_the_ranked_answer": lambda g, r: r.decision["subject"] not in (
        "MEASURED_MOVE",
        "FADING_MEASURED_MOVE",
    ),
    "the_projection_is_called_inverse": lambda g, r: all(
        m["family"] != "INVERSE" for m in r.measured_moves
    ),
}


def test_every_must_not_claim_is_implemented_and_holds() -> None:
    """A claim the suite cannot evaluate is not a claim.

    An unrecognised name is a failure rather than a skip, so a fixture cannot
    smuggle in a vacuous expectation under a name nobody implemented.
    """
    for golden in ALL.values():
        result = golden.analyze()
        for claim, why in golden.must_not.items():
            assert len(why) >= 20, (
                f"{golden.id}: the claim {claim!r} has no explanation, so it cannot"
                " be reviewed"
            )
            assert claim in MUST_NOT_CHECKS, (
                f"{golden.id} claims {claim!r}, which no test evaluates"
            )
            assert MUST_NOT_CHECKS[claim](golden, result) is True, (
                f"{golden.id}: {claim!r} is expected to hold and does not"
            )


# --------------------------------------------------------------------------
# The falsifiers -- the part a snapshot cannot do
# --------------------------------------------------------------------------


def _drop(golden: Golden, index: int) -> list[dict[str, float]]:
    return [dict(b) for i, b in enumerate(golden.bars) if i != index]


def test_removing_the_h2_resumption_makes_the_second_leg_provisional() -> None:
    """Falsifier 1 of `golden_h2_001`.

    Two counter-trend legs and no resumption is a *second leg*, not an entry. The
    old implementation called this H1, and `H1_H2_L1_L2.md` §3 records the fix —
    so this is the one mutation a regression would most plausibly reintroduce, and
    it is why the fixture pins `signal_bar` and not just `setup_type`.

    Lowering the resumption's high rather than deleting the bar matters: deleting
    it moves the window start from 40 to 39, which pulls an uptrend bar into the
    window and changes the first leg, so the test would pass for the wrong reason.
    """
    golden = ALL["golden_h2_001"]
    bars = [dict(b) for b in golden.bars]
    bars[52] = {"o": 112.6, "h": 114.1, "l": 112.5, "c": 114.0}
    setup = golden.setup("PULLBACK_H", golden.analyze(bars=bars, last_closed=52))

    assert setup["legs"] == 2, "the second leg is still there"
    assert setup["setup_type"] == "H2", "and it is still the second entry"
    assert setup["state"] == "PROVISIONAL"
    assert setup["signal_bar"] == -1, "no resumption means no entry bar"
    assert setup["anchor_bar"] == 50, "the first leg is unaffected"


def test_lifting_the_deeper_low_removes_the_second_leg() -> None:
    """Falsifier 2 of `golden_h2_001`: the level test, in isolation.

    Raise bar 51's low to 112.6, which is the level reached up to leg 1. The
    deeper low is then not deeper, so `leg2_low` is never found and the setup
    falls back to a first entry with one leg.
    """
    golden = ALL["golden_h2_001"]
    bars = [dict(b) for b in golden.bars]
    bars[51] = {"o": 114.1, "h": 114.2, "l": 112.6, "c": 112.8}
    setup = golden.setup("PULLBACK_H", golden.analyze(bars=bars, last_closed=52))

    assert setup["setup_type"] == "H1"
    assert setup["legs"] == 1
    assert setup["state"] == "PROVISIONAL"


def test_closing_the_breakout_bar_inside_the_tolerance_removes_the_breakout() -> None:
    """Falsifier 1 of `golden_breakout_001`.

    Close at 106.3 instead of 107.2. The threshold is `reference + 0.1 * atr` =
    106.399, so 106.3 is inside it and there is no breakout. This is what makes
    the tolerance a real boundary rather than a constant nobody has checked.
    """
    golden = ALL["golden_breakout_001"]
    bars = [dict(b) for b in golden.bars]
    bars[29] = {"o": 105.8, "h": 106.3, "l": 105.7, "c": 106.3}
    result = golden.analyze(bars=bars, last_closed=29)
    breakouts = [e for e in result.setups if e.get("detector") == "BREAKOUT"]

    assert breakouts == [], "a close inside the tolerance is not a breakout"


def test_closing_back_through_the_reference_fails_the_breakout() -> None:
    """Falsifier 2 of `golden_breakout_001`: failed takes precedence over pending."""
    golden = ALL["golden_breakout_001"]
    bars = [dict(b) for b in golden.bars]
    bars.append({"o": 107.2, "h": 107.3, "l": 104.8, "c": 105.0})
    result = golden.analyze(bars=bars, last_closed=30)
    setup = golden.setup("BREAKOUT", result)

    assert setup["outcome"] == "FAILED"
    assert setup["decide_bar"] == 30
    assert setup["state"] == "FAILED"


def test_holding_the_push_run_flat_removes_the_pressure_leg() -> None:
    """Falsifier 2 of `golden_mtr_001`.

    Hold bar 24's high level with bar 23's, so it makes no new high. The run of
    pushes breaks, `pressure_count` falls from 5 to 2, and the score drops from 75
    to 50. A reversal with no pressure behind it is a smaller claim, and the score
    is a count of legs, so it says so.
    """
    golden = ALL["golden_mtr_001"]
    bars = [dict(b) for b in golden.bars]
    bars[24] = {"o": 103.2, "h": 103.4, "l": 103.0, "c": 103.2}
    setup = golden.setup("REVERSAL_BULL", golden.analyze(bars=bars, last_closed=26))

    assert setup["pressure_ok"] is False
    assert setup["pressure_count"] == 2
    assert setup["score"] == 50
    assert setup["verdict"] == "MINOR", "2 legs is still a reversal, just a smaller one"


def test_separating_the_two_tops_removes_the_matching_half_of_the_gate() -> None:
    """Falsifier 1 of `golden_double_001`: the matching half of the gate.

    Bar 31's high to 107.5 puts it 1.3 above bar 29's 106.2, well outside the
    0.537 tolerance, so the pair cannot be a double.
    """
    golden = ALL["golden_double_001"]
    bars = [dict(b) for b in golden.bars]
    bars[31] = {"o": 103.6, "h": 107.5, "l": 103.5, "c": 104.2}
    result = golden.analyze(bars=bars, last_closed=31)
    tops = [
        e for e in result.setups
        if e.get("pattern_type") == "MICRO_DOUBLE_TOP"
        and e.get("bar1") == 29 and e.get("bar2") == 31
    ]

    assert tops == []


def test_lifting_the_trough_moves_the_double_rather_than_deleting_it() -> None:
    """Falsifier 2 of `golden_double_001`: the separation half, and its surprise.

    Lift bar 30's low to 105.9 and the (29, 31) pair stops qualifying, because
    separation must be at least `0.25 * atr`. The pattern is **not** removed: the
    detector scans every pair in the five-bar window and falls back to (28, 31),
    whose highs of 106.0 and 106.3 are separated by bar 29's 103.9 low.

    That is worth knowing rather than papering over. "Is there a double top?" has
    no answer here, because there is always some pair of similar highs in a range;
    the question the detector can answer is *which* pair, and it answers with the
    most recent one that clears the separation rule.
    """
    golden = ALL["golden_double_001"]
    bars = [dict(b) for b in golden.bars]
    bars[30] = {"o": 106.0, "h": 106.1, "l": 105.9, "c": 106.0}
    result = golden.analyze(bars=bars, last_closed=31)
    tops = [
        e for e in result.setups
        if e.get("pattern_type") == "MICRO_DOUBLE_TOP" and e.get("found")
    ]

    assert [(t["bar1"], t["bar2"]) for t in tops] == [(28, 31)], (
        "the pair should have moved earlier in the window, not vanished"
    )
    assert tops[0]["price1"] == pytest.approx(106.0)
    assert tops[0]["price2"] == pytest.approx(106.3)


def test_widening_the_measured_leg_moves_the_target_by_exactly_that_much() -> None:
    """Falsifier 2 of `golden_fm_001`: the projection arithmetic in isolation.

    Deepen A0 from 95.8 to 90.8, leaving A1 and B0 alone. `mm_range` grows from
    10.3 to 15.3, and the target must move from 111.1 to 100.8 + 15.3 = 116.1 —
    by exactly the 5.0 the leg grew, because the target is measured from the
    pullback low.

    An earlier draft of this falsifier tried to push the pullback depth below the
    0.15 floor and reach the CHANNEL family. It does not work, and the reason is
    worth keeping in mind: raising the pullback low also raises A1 or moves the
    swing, so the leg grows with it and the depth barely moves. Lifting one bar's
    low does not change the family at all — it just relocates the swing. The
    boundary is real and the depth of 0.5146 is nowhere near it, but reaching it
    takes a whole differently-shaped chart rather than an edit.
    """
    golden = ALL["golden_fm_001"]
    bars = [dict(b) for b in golden.bars]
    bars[12] = {"o": 93.0, "h": 93.2, "l": 90.8, "c": 91.0}
    moves = golden.analyze(bars=bars, last_closed=29).measured_moves
    move = next(m for m in moves if m["family"] == "REGULAR")

    assert move["a0"]["price"] == pytest.approx(90.8)
    assert move["a1"]["price"] == pytest.approx(106.1)
    assert move["b0"]["price"] == pytest.approx(100.8)
    assert move["mm_range"] == pytest.approx(15.3)
    assert move["target_price"] == pytest.approx(100.8 + 15.3)
    assert move["target_price"] == pytest.approx(116.1)


def test_the_fade_lifecycle_agrees_with_the_pipeline_when_the_target_is_never_reached() -> None:
    """Falsifier 1 of `golden_fm_001`, and the control for the finding it records.

    Truncate the series before price reaches the target. The lifecycle then never
    touches, and the pipeline's `PROJECTED` becomes *correct* rather than a
    limitation. That is the honest boundary of the finding: it is about having
    reached a target, not about the architecture failing for every fade.
    """
    golden = ALL["golden_fm_001"]
    truncated = [dict(b) for b in golden.bars[:27]]
    last = len(truncated) - 1
    cfg = golden.analyzer_config
    series = BarSeries(truncated)
    atr = calculate_atr_series(series, period=cfg.atr_period)[last]
    swings = find_swings(series, last_closed_idx=last, k=cfg.swing_k)
    legs = build_legs_from_swings(swings)
    tracked = track_fading_measured_moves(
        series, last_closed=last, atr=atr, swings=swings, legs=legs, config=cfg
    )

    assert tracked, "the projection should still be seeded"
    assert tracked[0].state == "POTENTIAL", "price is within 1.0*atr of the target"
    assert tracked[0].touched is False, "but it never got within 0.25*atr of it"


# --------------------------------------------------------------------------
# Nothing here is validation of an edge
# --------------------------------------------------------------------------


def test_the_dataset_claims_no_edge_and_no_forecast() -> None:
    """The words this project will not use, checked against its own fixtures.

    A validation dataset is precisely the artefact that could be mistaken for
    evidence that a setup works. These are detection fixtures over five
    hand-authored charts; they say what the engine *names*, and nothing about what
    follows. `VALIDATION.md` §6 says the same at length.
    """
    for golden in ALL.values():
        blob = json.dumps(golden.raw).lower()
        for forbidden in ("win rate", "winrate", "expectancy", "profit factor",
                          "equity curve", "edge", "forecast", "accuracy"):
            assert forbidden not in blob, f"{golden.id} uses {forbidden!r}"
        assert "valid" not in golden.concept.lower() or "validation" in golden.concept.lower()
